#ifndef DC_POWERMON_CMDS_H
#define DC_POWERMON_CMDS_H

#define DC_POWERMON_CMD_LINEFEED          "\n"
#define DC_POWERMON_RSP_LINEFEED          "\r\n"

#define DC_POWERMON_CMD_SYSTEM_EXIT       "SYS:EXIT" DC_POWERMON_CMD_LINEFEED
#define DC_POWERMON_CMD_RESET             "*RST" DC_POWERMON_CMD_LINEFEED
#define DC_POWERMON_CMD_ID                "*IDN?" DC_POWERMON_CMD_LINEFEED

#define DC_POWERMON_CMD_READ_POWER        "POWER:READ?" DC_POWERMON_CMD_LINEFEED
#define DC_POWERMON_CMD_READ_CURRENT      "CURR:READ?" DC_POWERMON_CMD_LINEFEED
#define DC_POWERMON_CMD_READ_V_BUS        "VOLT:BUS:READ?" DC_POWERMON_CMD_LINEFEED
#define DC_POWERMON_CMD_READ_V_SHUNT      "VOLT:SHUNT:READ?" DC_POWERMON_CMD_LINEFEED

#endif
